apiVersion: v1
kind: PersistentVolume
metadata:
  name: cast-db-pv
spec:
  capacity:
    storage: 5Gi  # You can adjust the size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fast
  hostPath:
    path: /data/postgres/cast_db  # Adjust the path based on your system or cloud provider
    type: DirectoryOrCreate
