apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  
spec:
  rules:
  - host: movie.example.com
    http:
      paths:
      - path: /api/v1/movies
        pathType: Prefix
        backend:
          service:
            name: movie-service
            port:
              number: 8001
  - host: cast.example.com
    http:
      paths:
      - path: /api/v1/cast
        pathType: Prefix
        backend:
          service:
            name: cast-service
            port:
              number: 8002