apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Make sure this matches the size of the PV
  storageClassName: manual

