apiVersion: v1
kind: PersistentVolume
metadata:
  name: movie-db-pv 
spec:
  capacity:
    storage: 10Gi  # You can adjust the size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /data/postgres/movies_db  # Adjust the path based on your system or cloud provider
    type: DirectoryOrCreate
